project:
  type: book

book:
  title: "Introduction to Quarto and Zotero Using RStudio"
  author: "Ohio Alliance for Population Health <br> Shelby Level"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Installation Instructions"
      chapters:
      - installation-mac.qmd
      - installation-windows.qmd
    - part: "Document Examples"
      chapters:
      - html-example.qmd
      - word-example.qmd

bibliography: references.bib

format:
  html:
    theme: lux
  pdf:
    documentclass: scrreprt
mainfont: 'Georgia'

editor: visual

